/* Generated by re2c 0.13.5 on Tue Feb 18 04:10:34 2014 */
#line 3 "Zend55/zend_language_scanner_defs.h"

enum YYCONDTYPE {
	yycST_IN_SCRIPTING,
	yycST_LOOKING_FOR_PROPERTY,
	yycST_BACKQUOTE,
	yycST_DOUBLE_QUOTES,
	yycST_HEREDOC,
	yycST_LOOKING_FOR_VARNAME,
	yycST_VAR_OFFSET,
	yycINITIAL,
	yycST_TRANSLATE,
	yycST_VAR_OFFSET_BY_DOT,
	yycST_END_HEREDOC,
	yycST_NOWDOC,
};
